apiVersion: v1
kind: Service
metadata:
  name: nginx-publish-notready
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
