apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-root-httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: httpserver
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: httpserver
          imagePullPolicy: Always
          image: cncamp/httpserver:v1.0-nonroot
          ports:
            - containerPort: 80
      serviceAccount: fake-user
