apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productpage
    version: v2
  name: productpage-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      labels:
        app: productpage
        version: v2
    spec:
      containers:
        - image: cncamp/examples-bookinfo-productpage-v1:1.16.2-v2
          imagePullPolicy: IfNotPresent
          name: productpage
          ports:
            - containerPort: 9080
              protocol: TCP
          resources: {}
          securityContext:
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      serviceAccount: bookinfo-productpage
      serviceAccountName: bookinfo-productpage
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmp