apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
        - name: alpine
          image: alpine
          stdin: true
          tty: true
      hostNetwork: true
      nodeName: cadmin