apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "details"
spec:
  selector:
    matchLabels:
      app: details
  jwtRules:
    - issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.12/security/tools/jwt/samples/jwks.json"
